:alien: Update getting single Paw request
bdougherty/paw-javascript-fetch-generator pull request #1
Opened 2019-04-03 12:30 UTC by abdullahceylan

The extension was giving `JS Exception Line 36. TypeError: undefined is not an object (evaluating 'request.getLastExchange')` error when you try to generate a `fetch` request code. This PR fixes that.

2019-04-03 13:01 UTC, bdougherty requested changes
Thanks! Can you update the PR to include only the fix and not any formatting changes?

2019-04-03 13:22 UTC, abdullahceylan commented
Oops, sorry about that.

I've just updated.

2019-04-04 21:10 UTC, bdougherty approved these changes

2019-04-04 21:14 UTC, merged

2019-04-04 21:19 UTC, bdougherty commented
@abdullahceylan merged. Thanks again!

2019-04-04 22:00 UTC, abdullahceylan commented
Thanks to you too @bdougherty !